include:
  - board: xiao_ble//zmk
    shield: totem_left
  - board: xiao_ble//zmk
    shield: totem_right
  - board: xiao_ble//zmk
    shield: totem_dongle prospector_adapter
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: xiao_ble//zmk
    shield: settings_reset
  - board: xiao_ble//zmk
    shield: totem_left totem_esb_left
    artifact-name: totem_left_esb
  - board: xiao_ble//zmk
    shield: totem_right totem_esb_right
    artifact-name: totem_right_esb
  - board: xiao_ble//zmk
    shield: totem_dongle prospector_adapter totem_esb_dongle
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: totem_dongle_esb_prospector
