#!/usr/bin/env python3
# Copyright (c) 2026 asj9005
# SPDX-License-Identifier: MIT
"""Generate role-specific local key configuration files for Totem ESB v3.

The raw keys are written only to the requested files. Console output contains
paths and short SHA-256 fingerprints so matching files can be checked without
printing key material.
"""

from __future__ import annotations

import argparse
import hashlib
import os
from pathlib import Path
import secrets
import stat
import sys
import tempfile
from typing import Mapping, Optional


AES_128_KEY_BYTES = 16
FINGERPRINT_HEX_CHARS = 16

LOCAL_KEY_SYMBOL = "CONFIG_TOTEM_ESB_V3_LOCAL_KEY_HEX"
LEFT_KEY_SYMBOL = "CONFIG_TOTEM_ESB_V3_LEFT_KEY_HEX"
RIGHT_KEY_SYMBOL = "CONFIG_TOTEM_ESB_V3_RIGHT_KEY_HEX"


def short_fingerprint(key: bytes) -> str:
    """Return a non-secret, 64-bit display fingerprint for one key."""
    return hashlib.sha256(key).hexdigest()[:FINGERPRINT_HEX_CHARS]


def keyconf(symbols: Mapping[str, bytes]) -> str:
    """Serialize key bytes as an ASCII Zephyr configuration fragment."""
    lines = [
        "# Generated by tools/generate_esb_v3_keys.py.",
        "# Do not commit or upload this file or firmware built from it.",
    ]
    lines.extend(f'{symbol}="{key.hex()}"' for symbol, key in symbols.items())
    return "\n".join(lines) + "\n"


def stage_file(target: Path, contents: str) -> Path:
    """Write and fsync a temporary file beside its final target."""
    descriptor, temporary_name = tempfile.mkstemp(
        dir=target.parent,
        prefix=f".{target.name}.",
        suffix=".tmp",
        text=True,
    )
    temporary = Path(temporary_name)
    try:
        os.chmod(temporary, stat.S_IRUSR | stat.S_IWUSR)
        with os.fdopen(descriptor, "w", encoding="ascii", newline="\n") as stream:
            descriptor = -1
            stream.write(contents)
            stream.flush()
            os.fsync(stream.fileno())
    except BaseException:
        if descriptor >= 0:
            os.close(descriptor)
        temporary.unlink(missing_ok=True)
        raise
    return temporary


def write_key_files(output_dir: Path, *, force: bool) -> tuple[Path, Path, Path, str, str]:
    """Generate two independent keys and atomically replace each target file."""
    output_dir.mkdir(parents=True, exist_ok=True)

    left_path = output_dir / "left.keyconf"
    right_path = output_dir / "right.keyconf"
    dongle_path = output_dir / "dongle.keyconf"
    targets = (left_path, right_path, dongle_path)

    existing = [path for path in targets if path.exists()]
    if existing and not force:
        paths = ", ".join(str(path) for path in existing)
        raise FileExistsError(
            f"refusing to overwrite existing file(s): {paths}; pass --force to replace them"
        )

    left_key = secrets.token_bytes(AES_128_KEY_BYTES)
    right_key = secrets.token_bytes(AES_128_KEY_BYTES)
    while right_key == left_key:
        right_key = secrets.token_bytes(AES_128_KEY_BYTES)

    contents = {
        left_path: keyconf({LOCAL_KEY_SYMBOL: left_key}),
        right_path: keyconf({LOCAL_KEY_SYMBOL: right_key}),
        dongle_path: keyconf(
            {
                LEFT_KEY_SYMBOL: left_key,
                RIGHT_KEY_SYMBOL: right_key,
            }
        ),
    }

    staged: dict[Path, Path] = {}
    try:
        # Stage every file first so a serialization/write failure cannot leave
        # a mixture of newly generated final files.
        for target, text in contents.items():
            staged[target] = stage_file(target, text)

        # os.replace is atomic for a file when source and destination are in
        # the same directory. There is no portable three-file atomic commit.
        for target in targets:
            os.replace(staged[target], target)
            staged.pop(target)
            os.chmod(target, stat.S_IRUSR | stat.S_IWUSR)
    finally:
        for temporary in staged.values():
            temporary.unlink(missing_ok=True)

    return (
        left_path.resolve(),
        right_path.resolve(),
        dongle_path.resolve(),
        short_fingerprint(left_key),
        short_fingerprint(right_key),
    )


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Generate independent AES-128 keys and role-specific ESB v3 "
            "Zephyr configuration fragments."
        )
    )
    parser.add_argument(
        "output_dir",
        type=Path,
        help="directory that will receive left.keyconf, right.keyconf, and dongle.keyconf",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="atomically replace existing role configuration files",
    )
    return parser


def main(argv: Optional[list[str]] = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        left_path, right_path, dongle_path, left_fingerprint, right_fingerprint = (
            write_key_files(args.output_dir, force=args.force)
        )
    except (FileExistsError, OSError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 2

    print(f"left   sha256-64={left_fingerprint} path={left_path}")
    print(f"right  sha256-64={right_fingerprint} path={right_path}")
    print(
        "dongle "
        f"left-sha256-64={left_fingerprint} "
        f"right-sha256-64={right_fingerprint} "
        f"path={dongle_path}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
